services:
  vault:
    image: vault:1.15
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: sentinel
    ports:
      - "8200:8200"

  sentinelapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - vault
